/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context } from "./src/context"
import type { core } from "nexus"
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    /**
     * A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    dateTime<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "DateTime";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    /**
     * A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    dateTime<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "DateTime";
  }
}


declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  CategoryOrderByInput: { // input type
    createdAt?: NexusGenEnums['Sorting'] | null; // Sorting
    name?: NexusGenEnums['Sorting'] | null; // Sorting
  }
  FlashcardOrderByInput: { // input type
    answer?: NexusGenEnums['Sort'] | null; // Sort
    createdAt?: NexusGenEnums['Sort'] | null; // Sort
    question?: NexusGenEnums['Sort'] | null; // Sort
  }
}

export interface NexusGenEnums {
  Role: "ADMIN" | "USER"
  Sort: "asc" | "desc"
  Sorting: "asc" | "desc"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  DateTime: any
}

export interface NexusGenObjects {
  AllCategories: { // root type
    categories: Array<NexusGenRootTypes['Category'] | null>; // [Category]!
    count: number; // Int!
    id?: string | null; // ID
  }
  AllFlashcards: { // root type
    flashcards: Array<NexusGenRootTypes['Flashcard'] | null>; // [Flashcard]!
  }
  AllUser: { // root type
    users: Array<NexusGenRootTypes['User'] | null>; // [User]!
  }
  AuthPayload: { // root type
    token: string; // String!
    user: NexusGenRootTypes['User']; // User!
  }
  Category: { // root type
    createdAt: string; // String!
    description: string; // String!
    id: number; // Int!
    name: string; // String!
  }
  Flashcard: { // root type
    answer: string; // String!
    createdAt: string; // String!
    id: number; // Int!
    isReady: boolean; // Boolean!
    question: string; // String!
  }
  Mutation: {};
  Query: {};
  User: { // root type
    email: string; // String!
    id: number; // Int!
    name: string; // String!
    role: NexusGenEnums['Role']; // Role!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  AllCategories: { // field return type
    categories: Array<NexusGenRootTypes['Category'] | null>; // [Category]!
    count: number; // Int!
    id: string | null; // ID
  }
  AllFlashcards: { // field return type
    flashcards: Array<NexusGenRootTypes['Flashcard'] | null>; // [Flashcard]!
  }
  AllUser: { // field return type
    users: Array<NexusGenRootTypes['User'] | null>; // [User]!
  }
  AuthPayload: { // field return type
    token: string; // String!
    user: NexusGenRootTypes['User']; // User!
  }
  Category: { // field return type
    categoryCreator: NexusGenRootTypes['User'] | null; // User
    createdAt: string; // String!
    description: string; // String!
    id: number; // Int!
    name: string; // String!
  }
  Flashcard: { // field return type
    answer: string; // String!
    category: NexusGenRootTypes['Category'] | null; // Category
    createdAt: string; // String!
    flashCardCreator: NexusGenRootTypes['User'] | null; // User
    id: number; // Int!
    isReady: boolean; // Boolean!
    question: string; // String!
  }
  Mutation: { // field return type
    assignRole: NexusGenRootTypes['User']; // User!
    createCategory: NexusGenRootTypes['Category']; // Category!
    createFlashcard: NexusGenRootTypes['Flashcard'] | null; // Flashcard
    deleteCategory: NexusGenRootTypes['Category']; // Category!
    deleteFlashcard: NexusGenRootTypes['Flashcard']; // Flashcard!
    login: NexusGenRootTypes['AuthPayload']; // AuthPayload!
    signup: NexusGenRootTypes['User']; // User!
    updateCategory: NexusGenRootTypes['Category']; // Category!
    updateFlashcard: NexusGenRootTypes['Flashcard']; // Flashcard!
  }
  Query: { // field return type
    categories: NexusGenRootTypes['AllCategories']; // AllCategories!
    category: NexusGenRootTypes['Category']; // Category!
    flashcard: NexusGenRootTypes['Flashcard']; // Flashcard!
    flashcards: NexusGenRootTypes['AllFlashcards']; // AllFlashcards!
    user: NexusGenRootTypes['User']; // User!
    users: NexusGenRootTypes['AllUser']; // AllUser!
  }
  User: { // field return type
    categories: NexusGenRootTypes['Category'][]; // [Category!]!
    email: string; // String!
    flashcards: NexusGenRootTypes['Flashcard'][]; // [Flashcard!]!
    id: number; // Int!
    name: string; // String!
    role: NexusGenEnums['Role']; // Role!
  }
}

export interface NexusGenFieldTypeNames {
  AllCategories: { // field return type name
    categories: 'Category'
    count: 'Int'
    id: 'ID'
  }
  AllFlashcards: { // field return type name
    flashcards: 'Flashcard'
  }
  AllUser: { // field return type name
    users: 'User'
  }
  AuthPayload: { // field return type name
    token: 'String'
    user: 'User'
  }
  Category: { // field return type name
    categoryCreator: 'User'
    createdAt: 'String'
    description: 'String'
    id: 'Int'
    name: 'String'
  }
  Flashcard: { // field return type name
    answer: 'String'
    category: 'Category'
    createdAt: 'String'
    flashCardCreator: 'User'
    id: 'Int'
    isReady: 'Boolean'
    question: 'String'
  }
  Mutation: { // field return type name
    assignRole: 'User'
    createCategory: 'Category'
    createFlashcard: 'Flashcard'
    deleteCategory: 'Category'
    deleteFlashcard: 'Flashcard'
    login: 'AuthPayload'
    signup: 'User'
    updateCategory: 'Category'
    updateFlashcard: 'Flashcard'
  }
  Query: { // field return type name
    categories: 'AllCategories'
    category: 'Category'
    flashcard: 'Flashcard'
    flashcards: 'AllFlashcards'
    user: 'User'
    users: 'AllUser'
  }
  User: { // field return type name
    categories: 'Category'
    email: 'String'
    flashcards: 'Flashcard'
    id: 'Int'
    name: 'String'
    role: 'Role'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    assignRole: { // args
      index: number; // Int!
      role: NexusGenEnums['Role']; // Role!
    }
    createCategory: { // args
      description: string; // String!
      name: string; // String!
    }
    createFlashcard: { // args
      answer: string; // String!
      category: string; // String!
      question: string; // String!
    }
    deleteCategory: { // args
      id: number; // Int!
    }
    deleteFlashcard: { // args
      id: number; // Int!
    }
    login: { // args
      email: string; // String!
      password: string; // String!
    }
    signup: { // args
      email: string; // String!
      name: string; // String!
      password: string; // String!
    }
    updateCategory: { // args
      id: number; // Int!
      isActive?: boolean | null; // Boolean
      name?: string | null; // String
    }
    updateFlashcard: { // args
      answer?: string | null; // String
      category?: string | null; // String
      id: number; // Int!
      isReady?: boolean | null; // Boolean
      question?: string | null; // String
    }
  }
  Query: {
    categories: { // args
      filter?: string | null; // String
      orderBy?: NexusGenInputs['CategoryOrderByInput'][] | null; // [CategoryOrderByInput!]
      skip?: number | null; // Int
      take?: number | null; // Int
    }
    category: { // args
      index?: number | null; // Int
    }
    flashcard: { // args
      index?: number | null; // Int
    }
    flashcards: { // args
      filter?: string | null; // String
      orderBy?: NexusGenInputs['FlashcardOrderByInput'][] | null; // [FlashcardOrderByInput!]
      skip?: number | null; // Int
      take?: number | null; // Int
    }
    user: { // args
      index?: number | null; // Int
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}